import type { Metadata } from 'next'
import Image from 'next/image'




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex h-screen">
      <div className="hidden lg:flex items-center justify-center flex-1 bg-white text-black">
    <Image
src="/authpage.svg"
width={100}
height={100}
alt="auth_img"
className="max-w-md text-center w-full"

/>
     </div>
        {children}
        </main>
        </body>
    </html>
  )
}