import type { Metadata } from 'next'
import { Cairo } from 'next/font/google'
import './globals.css'
import { AddproductsProvider } from '@/context/HandelAddproducts'

const font = Cairo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      <AddproductsProvider>
        {children}
      </AddproductsProvider>
        </body>
    </html>
  )
}
